[build]
builder = "nixpacks"

[build.nixpacks]
# Cambiamos 'postgresql' por 'postgresql_17'
pkgs = ["php82", "php82Packages.composer", "postgresql_17"]

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"