[build]
builder = "nixpacks"

[build.nixpacks]
# Usamos postgresql-17 para asegurar compatibilidad total
pkgs = ["php82", "php82Packages.composer", "postgresql_17"]

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"